name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        uses: ./.github/composite-actions/install

      - name: Run linters
        run: pnpm lint

      - name: Run tests
        run: pnpm test:ci

